version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: always
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    networks:
      - accontant-network
    working_dir: /var/www

  app:
    image: awswadwk/accontant-app
    container_name: ${APP_NAME}
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    networks:
      - accontant-network

  mysql:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: ${APP_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - accountantData:/var/lib/mysql/
    networks:
      - accontant-network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: ${APP_NAME}-phpmyadmin
    ports:
      - "8182:80"
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    networks:
      - accontant-network

volumes:
  accountantData:
    driver: local

networks:
  accontant-network:
