name: Continuous Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy app to dev server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd public_html/accountancy_app
            git pull origin dev
            composer install
            php artisan migrate
            php artisan optimize
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
